### PR TITLE
added initial files

### PR DESCRIPTION
**Pull request by alexsaber89**

### CODE REVIEW

**Comment by JoeShep** [comment]
@alexsaber89, just confirming that you're still working on this, and you're not awaiting a review

**Comment by alexsaber89** [comment]
@JoeShep, yes sir, still trying to get the tree function working!

**Comment by alexsaber89** [comment]
@JoeShep, @zoeames, @ncgonz, quiz ready for review.

**Comment by JoeShep** [comment]
Alex, this looks great. I really don't have anything to add. You're demonstrating a very good grasp of JS basics. Even your commit history and commit names are great. This is ready to merge 👍

**Comment by alexsaber89** [comment]
@JoeShep, awesome!  Thank you very much!

**Pull request merged**
